AMINE_ACIDS_SMILES = {
    "A": "N[C@]([H])(C)C(=O)",
    "C": "N[C@]([H])(CS)C(=O)",
    "R": "N[C@]([H])(CCCNC(=N)N)C(=O)",
    "N": "N[C@@]([H])(CC(=O)N)C(=O)",
    "D": "N[C@@]([H])(CC(=O)O)C(=O)",
    "Q": "N[C@@]([H])(CCC(=O)N)C(=O)",
    "E": "N[C@@]([H])(CCC(=O)O)C(=O)",
    "G": "N[C@]([H])(C(=O)O)C(=O)",
    "H": "N[C@@]([H])(CC1=CN=CN1)C(=O)",
    "I": "N[C@@]([H])(CCC)C(=O)",
    "L": "N[C@@]([H])(CC)C(=O)",
    "K": "N[C@@]([H])(CCCNC(=O)N)C(=O)",
    "M": "N[C@@]([H])(CCSC)C(=O)",
    "F": "N[C@@]([H])(CC1=CC=CC=C1)C(=O)",
    "P": "N[C@@]([H])(CCC(=O)O)C(=O)",
    "S": "N[C@@]([H])(CO)C(=O)",
    "T": "N[C@@]([H])(CC(=O)S)C(=O)",
    "W": "N[C@@]([H])(CC1=CC=C(C=C1)O)C(=O)",
    "Y": "N[C@@]([H])(CC1=CC=C(O)C=C1)C(=O)",
    "V": "N[C@@]([H])(C(C)C)C(=O)",
    "U": "N[C@]([H])(C(=O)O)C(=O)",
}

# |------------------------------------------------------------------------------|#
